name: eastwood


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - name: Cache gitlibs
        uses: actions/cache@v2
        with:
          path: ~/.gitlibs
          key: ${{ runner.os }}-gitlibs-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-gitlibs-


      - name: Set up graalvm
        uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '20.1.0.java11'


      - name: Install native-image
        run: gu install native-image


      - name: Set up clojure-cli
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.561'


      - name: json2edn native-image
        run: |
          cd json2edn
          clojure -A:native-image
